#!/bin/bash

# Script to split requirements by index source
# Packages from pypi.org go to requirements.source.txt
# Packages from console.redhat.com go to requirements.wheel.txt

# stop on error and print commands
set -ex

RAW_REQ_FILE="requirements.no_hashes.txt"
SOURCE_FILE="requirements.source.txt"
WHEEL_FILE="requirements.wheel.txt"
WHEEL_FILE_PYPI="requirements.wheel.pypi.txt"
SOURCE_HASH_FILE="requirements.hashes.source.txt"
WHEEL_HASH_FILE="requirements.hashes.wheel.txt"
WHEEL_HASH_FILE_PYPI="requirements.hashes.wheel.pypi.txt"
BUILD_FILE="requirements-build.txt"
RHOAI_INDEX_URL="https://console.redhat.com/api/pypi/public-rhai/rhoai/3.2/cpu-ubi9/simple/"

# extra wheels to be included in the wheel list, often come from build-time dependencies
EXTRA_WHEELS="uv-build,uv,pip,maturin"
# hf-xet: sdists require Rust edition 2024 (Cargo 1.85+); RHEL 9 has 1.84. Use wheel only.
# psycopg2-binary: wheel avoids needing pg_config / libpq-devel.
PYPI_WHEELS="opencv-python,omegaconf,rapidocr,sqlite-vec,griffe,griffecli,griffelib,pyclipper,tree-sitter-typescript,hf-xet,psycopg2-binary"

# Generate requirements list from pyproject.toml from both indexes
uv pip compile pyproject.toml -o "$RAW_REQ_FILE" \
		--python-platform x86_64-unknown-linux-gnu \
		--python-version 3.12 \
		--refresh \
		--index $RHOAI_INDEX_URL \
		--default-index https://pypi.org/simple/ \
		--index-strategy unsafe-best-match \
		--emit-index-annotation \
		--no-sources \
		--override requirements.overrides.txt

# Initialize output files
echo "# Packages from pypi.org" > "$SOURCE_FILE"
echo "# This file was autogenerated by konflux_requirements.sh" >> "$SOURCE_FILE"
echo "# Packages from console.redhat.com" > "$WHEEL_FILE"
echo "# This file was autogenerated by konflux_requirements.sh" >> "$WHEEL_FILE"
echo "--index-url $RHOAI_INDEX_URL" >> "$WHEEL_FILE"
echo "# Packages from pypi.org to be fetched as wheels" > "$WHEEL_FILE_PYPI"
echo "# This file was autogenerated by konflux_requirements.sh" >> "$WHEEL_FILE_PYPI"

current_package=""

while IFS= read -r line || [[ -n "$line" ]]; do
    # Check if this is a package line (starts with a letter/digit, not whitespace or #)
    if [[ "$line" =~ ^[a-zA-Z0-9] ]]; then
        current_package="$line"
    # Check if this is a "# from" annotation line
    elif [[ "$line" =~ ^[[:space:]]*#[[:space:]]*from[[:space:]]+(.*) ]]; then
        index_url="${BASH_REMATCH[1]}"

        if [[ -n "$current_package" ]]; then
            if [[ "$index_url" == "https://pypi.org/simple/" ]]; then
                # Extract package name (without version) for comparison
                package_name=$(echo "$current_package" | sed 's/[=<>!].*//')
                if echo ",${PYPI_WHEELS}," | grep -qF ",${package_name},"; then
                    echo "$current_package" >> "$WHEEL_FILE_PYPI"
                else
                    echo "$current_package" >> "$SOURCE_FILE"
                fi
            elif [[ "$index_url" == "$RHOAI_INDEX_URL" ]]; then
                echo "$current_package" >> "$WHEEL_FILE"
            fi
            current_package=""
        fi
    fi
done < "$RAW_REQ_FILE"

# hf-xet: optional/transitive; must be wheel-only (Rust edition 2024 / Cargo 1.85+).
# Always compile hashes from PyPI only: RHOAI mirrors can serve the same version with a
# different wheel digest than pypi.org, which breaks pip --require-hashes when both files
# are used (Containerfile installs requirements.hashes.wheel.txt before .pypi.txt).
if hf_xet_line=$(grep -E '^hf-xet==' "$WHEEL_FILE" || true); then
    grep -vE '^hf-xet==' "$WHEEL_FILE" > "${WHEEL_FILE}.tmp" && mv "${WHEEL_FILE}.tmp" "$WHEEL_FILE"
    if ! grep -qE '^hf-xet==' "$WHEEL_FILE_PYPI"; then
        echo "$hf_xet_line" >> "$WHEEL_FILE_PYPI"
    fi
fi
if ! grep -qE '^hf-xet==' "$WHEEL_FILE_PYPI"; then
    echo "hf-xet==1.2.0" >> "$WHEEL_FILE_PYPI"
fi

# replace the list of binary packages in konflux pipeline configuration
# only the package names, not the versions, delimited by commas
wheel_packages=$(grep -v "^[#-]" "$WHEEL_FILE" | sed 's/==.*//' | tr '\n' ',' | sed 's/,$//')
# append extra wheels to the list
wheel_packages="$wheel_packages,$EXTRA_WHEELS,$PYPI_WHEELS"
sed -i 's/"packages": "[^"]*"/"packages": "'"$wheel_packages"'"/' .tekton/rag-tool-pull-request.yaml
sed -i 's/"packages": "[^"]*"/"packages": "'"$wheel_packages"'"/' .tekton/rag-tool-push.yaml

echo "Packages from pypi.org written to: $SOURCE_FILE ($(wc -l < "$SOURCE_FILE") packages)"
echo "Packages from console.redhat.com written to: $WHEEL_FILE ($(wc -l < "$WHEEL_FILE") packages)"


# Use stdout redirection instead of -o flag to work around uv bug where -o reuses stale hashes from existing output file
uv pip compile "$WHEEL_FILE" --refresh --generate-hashes --index-url $RHOAI_INDEX_URL --python-version 3.12 --emit-index-url --no-deps --no-annotate --universal > "$WHEEL_HASH_FILE"
uv pip compile "$WHEEL_FILE_PYPI" --refresh --generate-hashes --python-version 3.12 --emit-index-url --no-deps --no-annotate > "$WHEEL_HASH_FILE_PYPI"
uv pip compile "$SOURCE_FILE" --refresh --generate-hashes --python-version 3.12 --emit-index-url --no-deps --no-annotate > "$SOURCE_HASH_FILE"
uv run pybuild-deps compile --output-file="$BUILD_FILE" "$SOURCE_FILE"

# pin maturin to the version available in the Red Hat registry
sed -i 's/maturin==[0-9.]*/maturin==1.10.2/' "$BUILD_FILE"

# remove intermediate files
rm "$RAW_REQ_FILE" "$WHEEL_FILE" "$WHEEL_FILE_PYPI" "$SOURCE_FILE"

echo "Done!"
echo "Packages from pypi.org written to: $SOURCE_HASH_FILE ($( grep -Eo '==[0-9.]+' "$SOURCE_HASH_FILE" | wc -l) packages)"
echo "Packages from console.redhat.com written to: $WHEEL_HASH_FILE ($(grep -Eo '==[0-9.]+' "$WHEEL_HASH_FILE" | wc -l) packages)"
echo "Packages from pypi.org (wheels) written to: $WHEEL_HASH_FILE_PYPI ($(grep -Eo '==[0-9.]+' "$WHEEL_HASH_FILE_PYPI" | wc -l) packages)"
echo "Build dependencies written to: $BUILD_FILE ($(grep -Eo '==[0-9.]+' "$BUILD_FILE" | wc -l) packages)"
echo "Remember to commit $SOURCE_HASH_FILE, $WHEEL_HASH_FILE, $WHEEL_HASH_FILE_PYPI, $BUILD_FILE, pipeline configurations and push the changes"