#!/bin/bash

# Generate hermetic requirements for CUDA Konflux build.
# Uses a copy of pyproject.toml with pytorch-cpu index removed so torch/torchvision
# resolve from default PyPI (CUDA wheels). Same split as CPU: RHOAI wheels vs PyPI.

set -ex

RAW_REQ_FILE="requirements.no_hashes.cuda.txt"
SOURCE_FILE="requirements.source.cuda.txt"
WHEEL_FILE="requirements.wheel.cuda.txt"
WHEEL_FILE_PYPI="requirements.wheel.pypi.cuda.txt"
SOURCE_HASH_FILE="requirements.hashes.source.cuda.txt"
WHEEL_HASH_FILE="requirements.hashes.wheel.cuda.txt"
WHEEL_HASH_FILE_PYPI="requirements.hashes.wheel.pypi.cuda.txt"
BUILD_FILE="requirements-build.cuda.txt"
RHOAI_INDEX_URL="https://console.redhat.com/api/pypi/public-rhai/rhoai/3.3/cuda12.9-ubi9/simple/"

EXTRA_WHEELS="uv-build,uv,pip,maturin"
# PyPI packages to fetch as binary wheels (no source build). Includes torch/CUDA and nvidia-* (binary-only on PyPI).
# hf-xet omitted: prefetch-dependencies cannot fetch from PyPI (uses RHOAI only), and sdists need Rust 1.85+.
PYPI_WHEELS="opencv-python,omegaconf,rapidocr,sqlite-vec,griffe,griffecli,griffelib,pyclipper,tree-sitter-typescript,torch,torchvision"
# nvidia-* packages (torch CUDA deps) are binary-only; match by prefix in the split loop below.

# Copy pyproject and remove pytorch-cpu so torch/torchvision come from default PyPI (CUDA).
# uv pip compile only accepts pyproject.toml, so swap temporarily.
cp pyproject.toml pyproject.cpu.bak.toml
cp pyproject.toml pyproject.cuda.toml
uv run python ./scripts/remove_pytorch_cpu_pyproject.py pyproject.cuda.toml
mv pyproject.toml pyproject.toml.cpu-only
mv pyproject.cuda.toml pyproject.toml

# Generate requirements from CUDA pyproject (torch from PyPI = CUDA on Linux)
uv pip compile pyproject.toml -o "$RAW_REQ_FILE" \
	--python-version 3.12 \
	--refresh \
	--index "$RHOAI_INDEX_URL" \
	--default-index https://pypi.org/simple/ \
	--index-strategy unsafe-best-match \
	--emit-index-annotation \
	--no-sources \
	--override requirements.overrides.cuda.txt

# Restore original pyproject.toml
mv pyproject.toml pyproject.cuda.toml
mv pyproject.toml.cpu-only pyproject.toml
rm -f pyproject.cpu.bak.toml

# Initialize output files
echo "# Packages from pypi.org (CUDA build)" > "$SOURCE_FILE"
echo "# This file was autogenerated by konflux_requirements_cuda.sh" >> "$SOURCE_FILE"
echo "# Packages from console.redhat.com" > "$WHEEL_FILE"
echo "# This file was autogenerated by konflux_requirements_cuda.sh" >> "$WHEEL_FILE"
echo "--index-url $RHOAI_INDEX_URL" >> "$WHEEL_FILE"
echo "# Packages from pypi.org to be fetched as wheels" > "$WHEEL_FILE_PYPI"
echo "# This file was autogenerated by konflux_requirements_cuda.sh" >> "$WHEEL_FILE_PYPI"

current_package=""
while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^[a-zA-Z0-9] ]]; then
        current_package="$line"
    elif [[ "$line" =~ ^[[:space:]]*#[[:space:]]*from[[:space:]]+(.*) ]]; then
        index_url="${BASH_REMATCH[1]}"
        if [[ -n "$current_package" ]]; then
            if [[ "$index_url" == "https://pypi.org/simple/" ]]; then
                package_name=$(echo "$current_package" | sed 's/[=<>!].*//')
                if echo ",${PYPI_WHEELS}," | grep -qF ",${package_name}," || [[ "$package_name" == nvidia-* ]]; then
                    echo "$current_package" >> "$WHEEL_FILE_PYPI"
                else
                    echo "$current_package" >> "$SOURCE_FILE"
                fi
            elif [[ "$index_url" == "$RHOAI_INDEX_URL" ]]; then
                echo "$current_package" >> "$WHEEL_FILE"
            fi
            current_package=""
        fi
    fi
done < "$RAW_REQ_FILE"

# Update CUDA pipeline configs with binary package list (RHOAI + extra + PyPI wheels including torch/nvidia-*)
wheel_packages=$(grep -v "^[#-]" "$WHEEL_FILE" | sed 's/==.*//' | tr '\n' ',' | sed 's/,$//')
pypi_wheel_packages=$(grep -v "^[#-]" "$WHEEL_FILE_PYPI" | sed 's/==.*//' | tr '\n' ',' | sed 's/,$//')
wheel_packages="$wheel_packages,$EXTRA_WHEELS,$PYPI_WHEELS,$pypi_wheel_packages"
for f in .tekton/rag-tool-pull-request-cuda.yaml .tekton/rag-tool-push-cuda.yaml; do
    if [[ -f "$f" ]]; then
        sed -i 's/"packages": "[^"]*"/"packages": "'"$wheel_packages"'"/' "$f"
    fi
done

echo "Packages from pypi.org written to: $SOURCE_FILE ($(wc -l < "$SOURCE_FILE") packages)"
echo "Packages from console.redhat.com written to: $WHEEL_FILE ($(wc -l < "$WHEEL_FILE") packages)"

# Generate hashed requirement files
uv pip compile "$WHEEL_FILE" --refresh --generate-hashes --index-url "$RHOAI_INDEX_URL" --python-version 3.12 --emit-index-url --no-deps --no-annotate --universal > "$WHEEL_HASH_FILE"
uv pip compile "$WHEEL_FILE_PYPI" --refresh --generate-hashes --python-version 3.12 --emit-index-url --no-deps --no-annotate > "$WHEEL_HASH_FILE_PYPI"
uv pip compile "$SOURCE_FILE" --refresh --generate-hashes --python-version 3.12 --emit-index-url --no-deps --no-annotate > "$SOURCE_HASH_FILE"
# Prefetch cannot fetch from PyPI; omit hf-xet so hermetic build succeeds (huggingface_hub works without it).
awk '/^hf-xet==/{skip=1; next} skip && /^[a-zA-Z0-9][a-zA-Z0-9_.-]*==/{skip=0} !skip{print}' "$SOURCE_HASH_FILE" > "$SOURCE_HASH_FILE.tmp" && mv "$SOURCE_HASH_FILE.tmp" "$SOURCE_HASH_FILE"
uv run pybuild-deps compile --output-file="$BUILD_FILE" "$SOURCE_FILE"

sed -i 's/maturin==[0-9.]*/maturin==1.10.2/' "$BUILD_FILE"

# Remove intermediate files
rm -f "$RAW_REQ_FILE" "$WHEEL_FILE" "$WHEEL_FILE_PYPI" "$SOURCE_FILE"

echo "Done!"
echo "Packages from pypi.org written to: $SOURCE_HASH_FILE ($(grep -Eo '==[0-9.]+' "$SOURCE_HASH_FILE" | wc -l) packages)"
echo "Packages from console.redhat.com written to: $WHEEL_HASH_FILE ($(grep -Eo '==[0-9.]+' "$WHEEL_HASH_FILE" | wc -l) packages)"
echo "Packages from pypi.org (wheels) written to: $WHEEL_HASH_FILE_PYPI ($(grep -Eo '==[0-9.]+' "$WHEEL_HASH_FILE_PYPI" | wc -l) packages)"
echo "Build dependencies written to: $BUILD_FILE ($(grep -Eo '==[0-9.]+' "$BUILD_FILE" | wc -l) packages)"
echo "Remember to commit the .cuda.txt requirement files, pipeline configurations and push the changes"
