#!/bin/bash

# Script to split requirements by index source.
#
# Policy (CPU hermetic):
#   1) RHOAI — If uv resolves a package from the RHOAI index, keep it on requirements.wheel.txt (RHOAI wheels).
#   2) PyPI — Prefer hashed sdists (requirements.hashes.source.txt / build from source at image build).
#   3) PyPI wheels — Only for packages listed in PYPI_WHEEL_LAST_RESORT (cannot use sdist in Hermeto/pip
#      reliably: Rust/C++ bootstrap, no sdist on PyPI, psycopg2-binary vs sdist, etc.). Add names here when
#      prefetch or build fails, not preemptively for every transitive.
#
# stop on error and print commands
set -ex

RAW_REQ_FILE="requirements.no_hashes.txt"
SOURCE_FILE="requirements.source.txt"
WHEEL_FILE="requirements.wheel.txt"
WHEEL_FILE_PYPI="requirements.wheel.pypi.txt"
SOURCE_HASH_FILE="requirements.hashes.source.txt"
WHEEL_HASH_FILE="requirements.hashes.wheel.txt"
WHEEL_HASH_CPU_X86="requirements.hashes.wheel.cpu.x86_64.txt"
WHEEL_HASH_CPU_AARCH="requirements.hashes.wheel.cpu.aarch64.txt"
WHEEL_HASH_FILE_PYPI="requirements.hashes.wheel.pypi.txt"
BUILD_FILE="requirements-build.txt"
RHOAI_INDEX_URL="https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.3/cpu-ubi9/simple/"

# Prefetch as wheels for image pip/bootstrap (not project deps).
EXTRA_WHEELS="uv-build,uv,pip,maturin"
# PyPI: wheel is last resort — expand this comma list only when hashed sdist path fails (Hermeto or Containerfile build).
# hf-xet / jiter: Rust sdists fragile under Hermeto; psycopg2-binary: avoid pg_config sdist path.
# tokenizers: PyPI publishes manylinux wheels; sdist requires Rust/cargo at image build — use wheel only.
# torch/torchvision/triton: if uv ever resolves these from PyPI, there is no practical sdist — wheels only.
PYPI_WHEEL_LAST_RESORT="hf-xet,psycopg2-binary,jiter,docling-parse,tokenizers,torch,torchvision,triton,opencv-python,rapidocr,sqlite-vec"

# Generate requirements list from pyproject.toml from both indexes
uv pip compile pyproject.toml -o "$RAW_REQ_FILE" \
		--python-platform x86_64-unknown-linux-gnu \
		--python-version 3.12 \
		--refresh \
		--index $RHOAI_INDEX_URL \
		--default-index https://pypi.org/simple/ \
		--index-strategy unsafe-best-match \
		--emit-index-annotation \
		--no-sources \
		--override requirements.overrides.txt

# Initialize output files
echo "# Packages from pypi.org" > "$SOURCE_FILE"
echo "# This file was autogenerated by konflux_requirements.sh" >> "$SOURCE_FILE"
echo "# Packages from packages.redhat.com" > "$WHEEL_FILE"
echo "# This file was autogenerated by konflux_requirements.sh" >> "$WHEEL_FILE"
echo "--index-url $RHOAI_INDEX_URL" >> "$WHEEL_FILE"
echo "# Packages from pypi.org to be fetched as wheels" > "$WHEEL_FILE_PYPI"
echo "# This file was autogenerated by konflux_requirements.sh" >> "$WHEEL_FILE_PYPI"

current_package=""

while IFS= read -r line || [[ -n "$line" ]]; do
    # Check if this is a package line (starts with a letter/digit, not whitespace or #)
    if [[ "$line" =~ ^[a-zA-Z0-9] ]]; then
        current_package="$line"
    # Check if this is a "# from" annotation line
    elif [[ "$line" =~ ^[[:space:]]*#[[:space:]]*from[[:space:]]+(.*) ]]; then
        index_url="${BASH_REMATCH[1]}"

        if [[ -n "$current_package" ]]; then
            if [[ "$index_url" == "https://pypi.org/simple/" ]]; then
                # Extract package name (without version) for comparison
                package_name=$(echo "$current_package" | sed 's/[=<>!].*//')
                if echo ",${PYPI_WHEEL_LAST_RESORT}," | grep -qF ",${package_name},"; then
                    echo "$current_package" >> "$WHEEL_FILE_PYPI"
                else
                    echo "$current_package" >> "$SOURCE_FILE"
                fi
            elif [[ "$index_url" == "$RHOAI_INDEX_URL" ]]; then
                echo "$current_package" >> "$WHEEL_FILE"
            fi
            current_package=""
        fi
    fi
done < "$RAW_REQ_FILE"

# hf-xet is optional/transitive; ensure wheel-only pin if compile did not emit it.
if ! grep -qE '^hf-xet==' "$WHEEL_FILE_PYPI"; then
    echo "hf-xet==1.2.0" >> "$WHEEL_FILE_PYPI"
fi

# Binary prefetch: RHOAI wheel names + PyPI last-resort wheels + bootstrap tools (Hermeto fetches wheels for these).
wheel_packages=$(grep -vE '^#|^--' "$WHEEL_FILE" | sed '/^$/d' | sed 's/==.*//' | tr '\n' ',' | sed 's/,$//')
pypi_wheel_packages=$(grep -vE '^#|^--' "$WHEEL_FILE_PYPI" | sed '/^$/d' | sed 's/==.*//' | tr '\n' ',' | sed 's/,$//')
wheel_packages="$wheel_packages,$EXTRA_WHEELS,$pypi_wheel_packages"
wheel_packages=$(printf '%s' "$wheel_packages" | tr ',' '\n' | awk 'NF && !seen[$0]++' | paste -sd, -)
for _tekton_prefetch in \
	.tekton/rag-tool-pull-request.yaml \
	.tekton/rag-tool-push.yaml \
	.tekton/lightspeed-core-rag-content-cpu-f176b-pull-request.yaml \
	.tekton/lightspeed-core-rag-content-cpu-f176b-push.yaml; do
	sed -i 's/"packages": "[^"]*"/"packages": "'"$wheel_packages"'"/' "$_tekton_prefetch"
done

echo "Packages from pypi.org written to: $SOURCE_FILE ($(wc -l < "$SOURCE_FILE") packages)"
echo "Packages from packages.redhat.com written to: $WHEEL_FILE ($(wc -l < "$WHEEL_FILE") packages)"


# Use stdout redirection instead of -o flag to work around uv bug where -o reuses stale hashes from existing output file
# Do NOT add PyPI as --extra-index-url here: uv would record PyPI wheel digests while Hermeto prefetches RHOAI rebuilds
# (*-N-*.whl), causing "checksum mismatch" / "No wheels found" for every such package.
# RHOAI simple must list wheels for --universal; if compile fails or is incomplete, add a direct pulp pin below.
# Hermeto/cachi2 prefetch does not support --extra-index-url in requirement files.
# RHOAI wheel pins (full set — not moved to PyPI for hash convenience).
if grep -qE '^[a-zA-Z0-9][a-zA-Z0-9_.-]*==' "$WHEEL_FILE"; then
	uv pip compile "$WHEEL_FILE" --refresh --generate-hashes \
		--index-url $RHOAI_INDEX_URL --index-strategy unsafe-best-match \
		--python-version 3.12 --emit-index-url --no-deps --no-annotate --universal > "$WHEEL_HASH_FILE"
else
	printf '%s\n' "# No RHOAI-only wheel pins; all other wheels use PyPI hashes in requirements.hashes.wheel.pypi.txt." > "$WHEEL_HASH_FILE"
	printf '%s\n' "--index-url $RHOAI_INDEX_URL" >> "$WHEEL_HASH_FILE"
fi
sed -i '/^--extra-index-url/d' "$WHEEL_HASH_FILE"
# Hermeto intersects torch==… + RHOAI index pins with PyPI wheel metadata; RHOAI rebuild filenames never
# match → "No wheels found". Strip torch/vision/triton from the RHOAI hash file and emit arch fragments
# with direct pulp / PyPI URLs (prefetch lists both; Containerfile picks one by TARGETARCH).
if grep -qE '^(torch|torchvision|triton)==' "$WHEEL_HASH_FILE"; then
	awk '
/^torch==|^torchvision==|^triton==/ { skip=1; next }
skip && /^[ \t]/ { next }
skip && /^[a-zA-Z0-9]/ { skip=0 }
{ print }
' "$WHEEL_HASH_FILE" > "${WHEEL_HASH_FILE}.strip" && mv "${WHEEL_HASH_FILE}.strip" "$WHEEL_HASH_FILE"
fi
# aiohappyeyeballs: RHOAI *-2-py3-none-any.whl ≠ PyPI bytes; Hermeto prefetches RHOAI → uv+PyPI hashes all rejected.
AIOHAPPYEYEBALLS_CPU_PULP_URL="https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.2/cpu-ubi9/aiohappyeyeballs-2.6.1-2-py3-none-any.whl"
AIOHAPPYEYEBALLS_CPU_PULP_SHA256="e63730c7e8303fe9b9b25dfdf72f49ed74380176609a5d11cf7b634058e986d9"
if grep -q '^aiohappyeyeballs==' "$WHEEL_HASH_FILE"; then
	awk -v url="$AIOHAPPYEYEBALLS_CPU_PULP_URL" -v wh="$AIOHAPPYEYEBALLS_CPU_PULP_SHA256" '
/^aiohappyeyeballs==/ {
  print "aiohappyeyeballs @ " url " \\"
  print "    --hash=sha256:" wh
  skip=1
  next
}
skip && /^[ \t]+--hash=/ { next }
skip && /^[[:space:]]*$/ { next }
skip && /^[a-zA-Z0-9]/ { skip=0 }
{ print }
' "$WHEEL_HASH_FILE" > "${WHEEL_HASH_FILE}.aioh" && mv "${WHEEL_HASH_FILE}.aioh" "$WHEEL_HASH_FILE"
fi
# aiohttp: RHOAI publishes separate linux_x86_64 / linux_aarch64 wheels. If both appear in the universal
# wheel file, pip installs every line and fails on the wrong arch ("not a supported wheel on this platform").
# Strip aiohttp from the main file and pin each arch in requirements.hashes.wheel.cpu.{x86_64,aarch64}.txt (like torch).
AIOHTTP_CPU_PULP_BASE="https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.2/cpu-ubi9"
AIOHTTP_CPU_X86_WHEEL="aiohttp-3.13.3-2-cp312-cp312-linux_x86_64.whl"
AIOHTTP_CPU_X86_SHA256="19f57e62cb4ee5baf6463ea09a386f91fd82d18bbb6f01fd69462ebb7493f1c6"
AIOHTTP_CPU_AARCH_WHEEL="aiohttp-3.13.3-2-cp312-cp312-linux_aarch64.whl"
AIOHTTP_CPU_AARCH_SHA256="3ad7241c57279824a2811527054c8c9ee7ed9d4c6d5fbdaba0e3a8ea95d294a4"
if grep -qE '^aiohttp(==| @)' "$WHEEL_HASH_FILE"; then
	awk '
/^aiohttp==|^aiohttp @/ { skip=1; next }
skip && /^[ \t]/ { next }
skip && /^[a-zA-Z0-9]/ { skip=0 }
{ print }
' "$WHEEL_HASH_FILE" > "${WHEEL_HASH_FILE}.stripaio" && mv "${WHEEL_HASH_FILE}.stripaio" "$WHEEL_HASH_FILE"
fi
# markupsafe: RHOAI *-2-cp312-*linux_*.whl bytes ≠ PyPI hashes in uv lock; Hermeto prefetches RHOAI. Split per
# arch (same pip issue as aiohttp if both arches appear in the universal wheel file).
MARKUPSAFE_CPU_PULP_BASE="https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.2/cpu-ubi9"
MARKUPSAFE_CPU_X86_WHEEL="markupsafe-3.0.3-2-cp312-cp312-linux_x86_64.whl"
MARKUPSAFE_CPU_X86_SHA256="0af6343bc5950d7402fac77cd858153863f2c6ea8fec825bf42b4a779617b228"
MARKUPSAFE_CPU_AARCH_WHEEL="markupsafe-3.0.3-2-cp312-cp312-linux_aarch64.whl"
MARKUPSAFE_CPU_AARCH_SHA256="fb13d952fc3e75323d200fedee7bd5c14341500afc2c5d7e0793ae369f933d1c"
if grep -qE '^markupsafe(==| @)' "$WHEEL_HASH_FILE"; then
	awk '
/^markupsafe==|^markupsafe @/ { skip=1; next }
skip && /^[ \t]/ { next }
skip && /^[a-zA-Z0-9]/ { skip=0 }
{ print }
' "$WHEEL_HASH_FILE" > "${WHEEL_HASH_FILE}.stripms" && mv "${WHEEL_HASH_FILE}.stripms" "$WHEEL_HASH_FILE"
fi
CPU_PULP_32="https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.2/cpu-ubi9"
TV_X86_URL="https://files.pythonhosted.org/packages/7e/e6/7324ead6793075a8c75c56abeed1236d1750de16a5613cfe2ddad164a92a/torchvision-0.24.0-cp312-cp312-manylinux_2_28_x86_64.whl"
TV_X86_SHA="26b9dd9c083f8e5f7ac827de6d5b88c615d9c582dc87666770fbdf16887e4c25"
TV_AARCH_URL="https://files.pythonhosted.org/packages/00/7b/e3809b3302caea9a12c13f3adebe4fef127188438e719fd6c8dc93db1da6/torchvision-0.24.0-cp312-cp312-manylinux_2_28_aarch64.whl"
TV_AARCH_SHA="b0531d1483fc322d7da0d83be52f0df860a75114ab87dbeeb9de765feaeda843"
{
	printf '%s\n' "# Autogenerated by konflux_requirements.sh — linux/x86_64 arch-specific wheels (Hermeto)."
	printf '%s\n' "torch @ ${CPU_PULP_32}/torch-2.9.0-7-cp312-cp312-linux_x86_64.whl \\"
	printf '%s\n' "    --hash=sha256:b6fa21f12a26a38f530f5afd691eaf7f632770034d80a1c66e4d9d52616cff07"
	printf '%s\n' "torchvision @ ${TV_X86_URL} \\"
	printf '%s\n' "    --hash=sha256:${TV_X86_SHA}"
	printf '%s\n' "triton @ ${CPU_PULP_32}/triton-3.5.0-3-cp312-cp312-linux_x86_64.whl \\"
	printf '%s\n' "    --hash=sha256:6f420ea77a5b22e4dffe502638da2e773a4dd8fbb016f1be140c9cfa81d313d9"
} > "$WHEEL_HASH_CPU_X86"
{
	printf '%s\n' "# Autogenerated by konflux_requirements.sh — linux/aarch64 arch-specific wheels (Hermeto)."
	printf '%s\n' "torch @ ${CPU_PULP_32}/torch-2.9.0-7-cp312-cp312-linux_aarch64.whl \\"
	printf '%s\n' "    --hash=sha256:dbef52f7f4824242a9cd9aff2ebd7e6c87744b5a40048cbb2e3854361ec727fd"
	printf '%s\n' "torchvision @ ${TV_AARCH_URL} \\"
	printf '%s\n' "    --hash=sha256:${TV_AARCH_SHA}"
	printf '%s\n' "triton @ ${CPU_PULP_32}/triton-3.5.0-3-cp312-cp312-linux_aarch64.whl \\"
	printf '%s\n' "    --hash=sha256:8325dca63029c7fedd3e70c11ba9abc472e94f54eaddfbe872a7d823d167e595"
} > "$WHEEL_HASH_CPU_AARCH"
if grep -qE '^aiohttp==' "$WHEEL_FILE"; then
	printf '%s\n' "aiohttp @ ${AIOHTTP_CPU_PULP_BASE}/${AIOHTTP_CPU_X86_WHEEL} \\" >> "$WHEEL_HASH_CPU_X86"
	printf '%s\n' "    --hash=sha256:${AIOHTTP_CPU_X86_SHA256}" >> "$WHEEL_HASH_CPU_X86"
	printf '%s\n' "aiohttp @ ${AIOHTTP_CPU_PULP_BASE}/${AIOHTTP_CPU_AARCH_WHEEL} \\" >> "$WHEEL_HASH_CPU_AARCH"
	printf '%s\n' "    --hash=sha256:${AIOHTTP_CPU_AARCH_SHA256}" >> "$WHEEL_HASH_CPU_AARCH"
fi
if grep -qE '^markupsafe==' "$WHEEL_FILE"; then
	printf '%s\n' "markupsafe @ ${MARKUPSAFE_CPU_PULP_BASE}/${MARKUPSAFE_CPU_X86_WHEEL} \\" >> "$WHEEL_HASH_CPU_X86"
	printf '%s\n' "    --hash=sha256:${MARKUPSAFE_CPU_X86_SHA256}" >> "$WHEEL_HASH_CPU_X86"
	printf '%s\n' "markupsafe @ ${MARKUPSAFE_CPU_PULP_BASE}/${MARKUPSAFE_CPU_AARCH_WHEEL} \\" >> "$WHEEL_HASH_CPU_AARCH"
	printf '%s\n' "    --hash=sha256:${MARKUPSAFE_CPU_AARCH_SHA256}" >> "$WHEEL_HASH_CPU_AARCH"
fi
if grep -qE '^[a-zA-Z0-9][a-zA-Z0-9_.-]*==' "$WHEEL_FILE_PYPI"; then
	uv pip compile "$WHEEL_FILE_PYPI" --refresh --generate-hashes --python-version 3.12 --emit-index-url --no-deps --no-annotate > "$WHEEL_HASH_FILE_PYPI"
else
	printf '%s\n' "# No PyPI wheel-only (last-resort) pins." > "$WHEEL_HASH_FILE_PYPI"
fi
# pylatexenc: Hermeto intersects binary wheel hashes with PyPI; RHOAI rebuild *-8-py3-none-any.whl does not match.
# Pin the pulp wheel (py3-none-any; same artifact is published on cuda12.9-ubi9 — not on 3.2/cpu-ubi9 pulp).
PYLATEXENC_CPU_PULP_URL="https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.3/cuda12.9-ubi9/pylatexenc-2.10-8-py3-none-any.whl"
PYLATEXENC_CPU_PULP_SHA256="df56e08b8c5aeea5d791c2e73cf91eaa746e8c52c0f1a51b249dcf033b6e10e6"
if grep -q '^pylatexenc==' "$WHEEL_HASH_FILE_PYPI"; then
	awk -v url="$PYLATEXENC_CPU_PULP_URL" -v wh="$PYLATEXENC_CPU_PULP_SHA256" '
/^pylatexenc==/ {
  print "pylatexenc @ " url " \\"
  print "    --hash=sha256:" wh
  skip=1
  next
}
skip && /^[ \t]+--hash=/ { next }
skip && /^[[:space:]]*$/ { next }
skip && /^[a-zA-Z0-9]/ { skip=0 }
{ print }
' "$WHEEL_HASH_FILE_PYPI" > "${WHEEL_HASH_FILE_PYPI}.plx" && mv "${WHEEL_HASH_FILE_PYPI}.plx" "$WHEEL_HASH_FILE_PYPI"
fi
# Hermeto fetches wheels per file index: RHOAI for .wheel.txt, PyPI for .pypi.txt. If a package
# appears in both, pip must see PyPI hashes (prefetched wheel). Drop the RHOAI copy (same as CUDA script).
awk 'FNR==NR { if (/^[a-zA-Z0-9].*(==| @ )/) { match($0, /^[a-zA-Z0-9][a-zA-Z0-9_.-]*/); p[substr($0,RSTART,RLENGTH)]=1 }; next }
     /^#/ { print; next }
     /^--index-url/ { print; next }
     /^[a-zA-Z0-9].*(==| @ )/ { match($0, /^[a-zA-Z0-9][a-zA-Z0-9_.-]*/); name=substr($0,RSTART,RLENGTH); skip=(name in p); if (!skip) print; next }
     { if (!skip) print }' "$WHEEL_HASH_FILE_PYPI" "$WHEEL_HASH_FILE" > "${WHEEL_HASH_FILE}.tmp" && mv "${WHEEL_HASH_FILE}.tmp" "$WHEEL_HASH_FILE"
# Same filter as pybuild-deps: never emit hashed source lines for CUDA stack / wheel-only pins into the
# CPU hermetic source file — Hermeto cannot satisfy them (e.g. nvidia-* has no usable sdist for fetch-deps).
grep -v -E '^(torch|torchvision|triton|faiss-cpu|nvidia-[a-zA-Z0-9_-]+)==' "$SOURCE_FILE" > "${SOURCE_FILE}.hashcompile"
uv pip compile "${SOURCE_FILE}.hashcompile" --refresh --generate-hashes --python-version 3.12 --emit-index-url --no-deps --no-annotate > "$SOURCE_HASH_FILE"
rm -f "${SOURCE_FILE}.hashcompile"
# pybuild-deps cannot fetch nvidia-* / torch stack sdists from PyPI; those are wheel-only in this image.
grep -v -E '^(torch|torchvision|triton|faiss-cpu|nvidia-[a-zA-Z0-9_-]+)==' "$SOURCE_FILE" > "${SOURCE_FILE}.build"
uv run pybuild-deps compile --output-file="$BUILD_FILE" "${SOURCE_FILE}.build"
rm -f "${SOURCE_FILE}.build"

# pin maturin to the version available in the Red Hat registry
sed -i 's/maturin==[0-9.]*/maturin==1.10.2/' "$BUILD_FILE"

# remove intermediate files
rm "$RAW_REQ_FILE" "$WHEEL_FILE" "$WHEEL_FILE_PYPI" "$SOURCE_FILE"

echo "Done!"
echo "Packages from pypi.org written to: $SOURCE_HASH_FILE ($( grep -Eo '==[0-9.]+' "$SOURCE_HASH_FILE" | wc -l) packages)"
echo "Packages from packages.redhat.com written to: $WHEEL_HASH_FILE ($(grep -Eo '==[0-9.]+' "$WHEEL_HASH_FILE" | wc -l) packages)"
echo "Packages from pypi.org (wheels) written to: $WHEEL_HASH_FILE_PYPI ($(grep -Eo '==[0-9.]+' "$WHEEL_HASH_FILE_PYPI" | wc -l) packages)"
echo "Build dependencies written to: $BUILD_FILE ($(grep -Eo '==[0-9.]+' "$BUILD_FILE" | wc -l) packages)"
echo "Remember to commit $SOURCE_HASH_FILE, $WHEEL_HASH_FILE, $WHEEL_HASH_CPU_X86, $WHEEL_HASH_CPU_AARCH, $WHEEL_HASH_FILE_PYPI, $BUILD_FILE, Containerfile, pipeline configurations and push the changes"
